env:
  # for more enviromnent presets, see
  # https://eslint.org/docs/4.0.0/user-guide/configuring#specifying-environments
  browser: true
  commonjs: true
  es6: true
  node: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  ecmaVersion: 8
  sourceType: module
rules:
  indent:
    - error
    - 2
  comma-dangle:
    - error
    - never
